# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  r2dbc:
    username: ecommerce
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YmY2ZTRjMzg0OWI0NjllNjNkYzI0YzI0YjY0OThiMDUzNmI5Mjc0MmYyZDE0OTFhOGMxNDliMmVlNzk5ZDhkODU1MGI0ZDU0MjhjM2IwOGE5MWU1OWUyYTNkYjJhMTUzYzQ2YjE5ODVlOGIyYmVhMGI5ODEwZGRmZGFjZDlhNjM=
