package br.com.andre.domain;

import static br.com.andre.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CustomerOrderItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerOrderItemAllPropertiesEquals(CustomerOrderItem expected, CustomerOrderItem actual) {
        assertCustomerOrderItemAutoGeneratedPropertiesEquals(expected, actual);
        assertCustomerOrderItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerOrderItemAllUpdatablePropertiesEquals(CustomerOrderItem expected, CustomerOrderItem actual) {
        assertCustomerOrderItemUpdatableFieldsEquals(expected, actual);
        assertCustomerOrderItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerOrderItemAutoGeneratedPropertiesEquals(CustomerOrderItem expected, CustomerOrderItem actual) {
        assertThat(actual)
            .as("Verify CustomerOrderItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerOrderItemUpdatableFieldsEquals(CustomerOrderItem expected, CustomerOrderItem actual) {
        assertThat(actual)
            .as("Verify CustomerOrderItem relevant properties")
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            )
            .satisfies(a ->
                assertThat(a.getTotalPrice())
                    .as("check totalPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalPrice())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCustomerOrderItemUpdatableRelationshipsEquals(CustomerOrderItem expected, CustomerOrderItem actual) {
        assertThat(actual)
            .as("Verify CustomerOrderItem relationships")
            .satisfies(a -> assertThat(a.getOrder()).as("check order").isEqualTo(expected.getOrder()))
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
