package br.com.andre.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShipmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentAllPropertiesEquals(Shipment expected, Shipment actual) {
        assertShipmentAutoGeneratedPropertiesEquals(expected, actual);
        assertShipmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentAllUpdatablePropertiesEquals(Shipment expected, Shipment actual) {
        assertShipmentUpdatableFieldsEquals(expected, actual);
        assertShipmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentAutoGeneratedPropertiesEquals(Shipment expected, Shipment actual) {
        assertThat(actual)
            .as("Verify Shipment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentUpdatableFieldsEquals(Shipment expected, Shipment actual) {
        assertThat(actual)
            .as("Verify Shipment relevant properties")
            .satisfies(a -> assertThat(a.getTrackingNumber()).as("check trackingNumber").isEqualTo(expected.getTrackingNumber()))
            .satisfies(a -> assertThat(a.getCarrier()).as("check carrier").isEqualTo(expected.getCarrier()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getShippedDate()).as("check shippedDate").isEqualTo(expected.getShippedDate()))
            .satisfies(a -> assertThat(a.getDeliveredDate()).as("check deliveredDate").isEqualTo(expected.getDeliveredDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentUpdatableRelationshipsEquals(Shipment expected, Shipment actual) {
        assertThat(actual)
            .as("Verify Shipment relationships")
            .satisfies(a -> assertThat(a.getOrder()).as("check order").isEqualTo(expected.getOrder()));
    }
}
