package br.com.andre.domain;

import static br.com.andre.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ShoppingCartItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShoppingCartItemAllPropertiesEquals(ShoppingCartItem expected, ShoppingCartItem actual) {
        assertShoppingCartItemAutoGeneratedPropertiesEquals(expected, actual);
        assertShoppingCartItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShoppingCartItemAllUpdatablePropertiesEquals(ShoppingCartItem expected, ShoppingCartItem actual) {
        assertShoppingCartItemUpdatableFieldsEquals(expected, actual);
        assertShoppingCartItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShoppingCartItemAutoGeneratedPropertiesEquals(ShoppingCartItem expected, ShoppingCartItem actual) {
        assertThat(actual)
            .as("Verify ShoppingCartItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShoppingCartItemUpdatableFieldsEquals(ShoppingCartItem expected, ShoppingCartItem actual) {
        assertThat(actual)
            .as("Verify ShoppingCartItem relevant properties")
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShoppingCartItemUpdatableRelationshipsEquals(ShoppingCartItem expected, ShoppingCartItem actual) {
        assertThat(actual)
            .as("Verify ShoppingCartItem relationships")
            .satisfies(a -> assertThat(a.getCart()).as("check cart").isEqualTo(expected.getCart()))
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
