export enum CustomerOrderStatus {
  CREATED = 'CREATED',

  WAITING_PAYMENT = 'WAITING_PAYMENT',

  PAID = 'PAID',

  SEPARATING = 'SEPARATING',

  SHIPPED = 'SHIPPED',

  DELIVERED = 'DELIVERED',

  CANCELLED = 'CANCELLED',

  REFUNDED = 'REFUNDED',
}
